# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    # Un admin hérite des droits d'auteur et de modérateur
    ROLE_ADMIN:       [ROLE_MEMBER, ROLE MODERATOR]
    # On garde ce rôle superadmin, il nous resservira par la suite
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
      in_memory:
        memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_MEMBER'] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN'] }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:      ^/
      anonymous:    true
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login

  access_control:
   




      
