# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #SnowTricks\HomeBundle\:
       # resource: '../../src/SnowTricks/HomeBundle/*'
       # exclude: '../../src/SnowTricks/HomeBundle/{Entity,Repository}'

    #SnowTricks\HomeBundle\Controller\:
        #resource: '../../src/SnowTricks/HomeBundle/Controller'
        #public: true
       #tags: ['controller.service_arguments']
    
   
