snow_tricks_home_homepage:
    path:     /{page}
    defaults: { _controller: SnowTricksHomeBundle:Tricks:home, page: 1 }
    requirements:
          page: \d+

snow_tricks_home_view:
    path:     /tricks/{slug}/{page}
    defaults: { _controller: SnowTricksHomeBundle:Tricks:view, page: 1 }
    requirements:
          
          page: \d*

snow_tricks_home_add:
    path:     /add 
    defaults: { _controller: SnowTricksHomeBundle:Tricks:add }

snow_tricks_home_edit:
    path:     /edit/{trick_id}
    defaults: { _controller: SnowTricksHomeBundle:Tricks:edit }
    requirements: 
           trick_id: \d+

snow_tricks_home_delete:
    path:     /delete/{trick_id}
    defaults: { _controller: SnowTricksHomeBundle:Tricks:delete }
    requirements:
           trick_id: \d+

snow_tricks_home_login:
    path:     /login
    defaults: { _controller: SnowTricksHomeBundle:Security:login }

snow_tricks_home_logout:
    path:     /logout
    defaults: { _controller: SnowTricksHomeBundle:Security:logout }

snow_tricks_home_register:
    path:     /register
    defaults: { _controller: SnowTricksHomeBundle:User:register }

snow_tricks_home_change_password:
    path:     /change
    defaults: { _controller: SnowTricksHomeBundle:User:changePassword }
    requirements:

snow_tricks_home_request_password:
    path:     /request
    defaults: { _controller: SnowTricksHomeBundle:User:requestPassword }

snow_tricks_home_reset_password:
    path:     /reset/{token}
    defaults: { _controller: SnowTricksHomeBundle:User:resetPassword }
    requirements:
        
        