services:
    snow_tricks_home.authenticator:
        class: SnowTricks\HomeBundle\Security\LoginFormAuthenticator
        autowire: true
        #arguments: ["@service_id", "plain_value", "%parameter%"]

    snow_tricks_home.hash_password_listener:
        class: SnowTricks\HomeBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
         - { name: doctrine.event_subscriber }

    snow_tricks_home.request_password_mail:
        class: SnowTricks\HomeBundle\EventListener\SendRequestPasswordMailListener
        arguments:
            - "@mailer"

    #snow_tricks_home.request_password:
        #class: SnowTricks\HomeBundle\EventListener\RequestListener
        #arguments: "@snow_tricks_home.request_password_mail"
        #tags:
            #- { name: kernel.event_listener, event: snow_tricks_homebundle.new_password_requested, method: processMail }